import pandas as pd
df = pd.read_csv(r'C:\Users\Mauro\Documents\databento-data\glbx-mdp3-20250203.trades.csv', low_memory=False)
df['ts_event'] = pd.to_datetime(df['ts_event'], utc=True)
df['price'] = df['price'].astype(float)
start = pd.Timestamp('2025-02-03 15:22:00', tz='UTC')
end = pd.Timestamp('2025-02-03 15:30:00', tz='UTC')
mask = (df['ts_event'] >= start) & (df['ts_event'] <= end)
subset = df.loc[mask, ['ts_event', 'price', 'size', 'side']].copy()
print(f'Trades from {start} to {end}: {len(subset)} records')
print(subset.head(20))
print('\nStats:')
print(subset['price'].describe())
print('\nOutliers beyond 3 std:')
mean = subset['price'].mean()
std = subset['price'].std()
outliers = subset[abs(subset['price'] - mean) > 3 * std]
print(outliers[['ts_event', 'price', 'size']])
# plot quick histogram (optional)
import matplotlib.pyplot as plt
plt.hist(subset['price'], bins=50)
plt.title('Price distribution 15:22-15:30')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.savefig('price_hist.png')
print('Histogram saved to price_hist.png')
# check if 21458 is plausible (maybe NQ moved 200+ points in seconds?)
# compute typical range
print(f'\nPrice range: {subset["price"].min():.2f} - {subset["price"].max():.2f}')
print(f'Median: {subset["price"].median():.2f}')
print(f'Std: {std:.2f}')